name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: npm install && brew tap mongodb/brew && brew install mongodb-community@5.0

      - name: Start MongoDB service
        run: brew services start mongodb-community@5.0

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # build: npm run build
          start: npm start
          wait-on: http://localhost:3030