name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: |
          npm install
          sudo apt-get install -y mongodb-community=5.0

      - name: Start MongoDB service
        run: sudo service mongod start

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # build: npm run build
          start: npm start
          wait-on: http://localhost:3030