name: Deploy

on:
  workflow_run:
    workflows: ["End-to-end tests"]
    types:
      - completed

jobs: 
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.MYAWSACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MYAWSSECRET_KEY }}
          aws-region: eu-west-2

      - name: Deploy to S3
        run: aws s3 sync . s3://bizzy-bees-bucket/